### ISSUE TITLE
webinar problema ao gerar usuário em lote 

### ISSUE THREAD

**Issue by magnussolution** [magnussolution/magnusbilling#29]
Error: You're trying to decode an invalid JSON String: <h1>PHP Error [2]</h1>
<p>Creating default object from empty value (/var/www/html/mbilling/protected/controllers/UserController.php:424)</p>
<pre>#0 /var/www/html/mbilling/protected/controllers/UserController.php(424): CWebApplication->handleError()
#1 /var/www/html/mbilling/yii/framework/web/actions/CInlineAction.php(49): UserController->actionBulk()
#2 /var/www/html/mbilling/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#3 /var/www/html/mbilling/yii/framework/web/CController.php(286): UserController->runAction()
#4 /var/www/html/mbilling/yii/framework/web/CController.php(265): UserController->runActionWithFilters()
#5 /var/www/html/mbilling/yii/framework/web/CWebApplication.php(282): UserController->run()
#6 /var/www/html/mbilling/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#7 /var/www/html/mbilling/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#8 /var/www/html/mbilling/index.php(12): CWebApplication->run()
</pre>

**Comment by magnussolution** [comment]
nao esta atualizando o credito do cliente
