### ISSUE TITLE
PHP Error[2]: include(MethodPay.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by viniciusbarretobr** [magnussolution/magnusbilling#480]
Devo me preocupar com estes erros? Como resolvê-los? 
Obrigado

**Erros que percebi:**
**1-** PHP Error[2]: include(MethodPay.php): failed to open stream: No such file or directory
```
PHP Error[2]: include(MethodPay.php): failed to open stream: No such file or directory
    in file /var/www/html/mbilling/yii/framework/YiiBase.php at line 421
#0 /var/www/html/mbilling/yii/framework/YiiBase.php(421): include()
#1 unknown(0): autoload()
#2 /var/www/html/mbilling/protected/commands/CryptocurrencyCommand.php(24): spl_autoload_call()
#3 /var/www/html/mbilling/yii/framework/console/CConsoleCommandRunner.php(67): CryptocurrencyCommand->run()
#4 /var/www/html/mbilling/yii/framework/console/CConsoleApplication.php(91): CConsoleCommandRunner->run()
#5 /var/www/html/mbilling/yii/framework/base/CApplication.php(169): CConsoleApplication->processRequest()
#6 /var/www/html/mbilling/cron.php(31): CConsoleApplication->run()
```

**2-** Também veio a mensagem abaixo e eu não sei exatamente se é um erro:

```
From root@voip-1.localdomain  Fri Nov  6 16:56:59 2020
Return-Path: <root@voip-1.localdomain>
X-Original-To: root
Delivered-To: root@voip-1.localdomain
From: "(Cron Daemon)" <root@voip-1.localdomain>
To: root@voip-1.localdomain
Subject: Cron <root@voip-1> php /var/www/html/mbilling/cron.php callchart
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
Precedence: bulk
X-Cron-Env: <XDG_SESSION_ID=8729>
X-Cron-Env: <XDG_RUNTIME_DIR=/run/user/0>
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
X-Cron-Env: <USER=root>
Date: Fri,  6 Nov 2020 16:47:01 -0300 (-03)
Status: R



START ------Array

use cdr show


START ------Array

use cdr show

totalUp é > total1
totalUp = 1 -> totalCalls = 1
this->totalUpCalls = 1 -> this->totalCalls = 1




START ------Array

use cdr show

totalUp = 1 -> totalCalls = 1
this->totalUpCalls = 1 -> this->totalCalls = 1




START ------Array

use cdr show

totalUp = 1 -> totalCalls = 1
this->totalUpCalls = 1 -> this->totalCalls = 1


START ------Array

use cdr show

totalUp = 1 -> totalCalls = 1
this->totalUpCalls = 1 -> this->totalCalls = 1

```

![image](https://user-images.githubusercontent.com/15203803/98409467-aeadd600-2051-11eb-8f87-32930fd9a22a.png)

![image](https://user-images.githubusercontent.com/15203803/98409476-b2415d00-2051-11eb-8aa7-60183bfca9e5.png)

**Comment by magnussolution** [comment]
solucionado
