### ISSUE TITLE
... cron.php cryptocurrency | PHP Error[2]: include(poloniex.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by viniciusbarretobr** [magnussolution/magnusbilling#485]
Emails com este erro estão sendo enviados para a conta local root (/var/spool/mail/root)

```
PHP Error[2]: include(poloniex.php): failed to open stream: No such file or directory
    in file /var/www/html/mbilling/yii/framework/YiiBase.php at line 421
#0 /var/www/html/mbilling/yii/framework/YiiBase.php(421): include()
#1 unknown(0): autoload()
#2 /var/www/html/mbilling/protected/commands/CryptocurrencyCommand.php(28): spl_autoload_call()
#3 /var/www/html/mbilling/yii/framework/console/CConsoleCommandRunner.php(67): CryptocurrencyCommand->run()
#4 /var/www/html/mbilling/yii/framework/console/CConsoleApplication.php(91): CConsoleCommandRunner->run()
#5 /var/www/html/mbilling/yii/framework/base/CApplication.php(169): CConsoleApplication->processRequest()
#6 /var/www/html/mbilling/cron.php(31): CConsoleApplication->run()
```

**Comment by viniciusbarretobr** [comment]
Email completo: 
```
From root@voip-1.localdomain  Wed Nov 25 04:33:01 2020
Return-Path: <root@voip-1.localdomain>
X-Original-To: root
Delivered-To: root@voip-1.localdomain
Received: by voip-1.localdomain (Postfix, from userid 0)
        id C576920B4719; Wed, 25 Nov 2020 04:33:01 -0300 (-03)
From: "(Cron Daemon)" <root@voip-1.localdomain>
To: root@voip-1.localdomain
Subject: Cron <root@voip-1> php /var/www/html/mbilling/cron.php cryptocurrency
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
Precedence: bulk
X-Cron-Env: <XDG_SESSION_ID=113871>
X-Cron-Env: <XDG_RUNTIME_DIR=/run/user/0>
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
X-Cron-Env: <USER=root>
Message-Id: <20201125073301.C576920B4719@voip-1.localdomain>
Date: Wed, 25 Nov 2020 04:33:01 -0300 (-03)

PHP Error[2]: include(poloniex.php): failed to open stream: No such file or directory
    in file /var/www/html/mbilling/yii/framework/YiiBase.php at line 421
#0 /var/www/html/mbilling/yii/framework/YiiBase.php(421): include()
#1 unknown(0): autoload()
#2 /var/www/html/mbilling/protected/commands/CryptocurrencyCommand.php(28): spl_autoload_call()
#3 /var/www/html/mbilling/yii/framework/console/CConsoleCommandRunner.php(67): CryptocurrencyCommand->run()
#4 /var/www/html/mbilling/yii/framework/console/CConsoleApplication.php(91): CConsoleCommandRunner->run()
#5 /var/www/html/mbilling/yii/framework/base/CApplication.php(169): CConsoleApplication->processRequest()
#6 /var/www/html/mbilling/cron.php(31): CConsoleApplication->run()
```

**Comment by magnussolution** [comment]
fixed, please update your magnusbilling
